const ACTIONS = {
  setActiveTab: "SET_ACTIVE_TAB",
  getDoctors: "GET_DOCTORS",
  getDoctor: "GET_DOCTOR",
  getPatients: "GET_PATIENTS",
  getPatient: "GET_PATIENT",
  getAppointments: "GET_APPOINTMENTS",
  getAppointment: "GET_APPOINTMENT",
  getAds: "GET_ADS",
  setAd: "SET_AD",
  setDoctor: "SET_DOCTOR",
  setUser: "SET_USER",
  logOut: "LOG_OUT",
  getBlogs: "GET_BLOGS",
  setBlog: "SET_BLOG",
  setBlogButton: "SET_BLOG_BUTTON",
  getPatientAlert: "GET_PATIENT_ALERTS",
  getDoctorAlert: "GET_DOCTOR_ALERTS",
  setAlert: "SET_ALERT",
  getReviews: "GET_REVIEWS",
  getReview: "GET_REVIEW",
  setDashboard: "SET_DASHBOARD",
  getContacts: "GET_CONTACTS",
  getContact: "GET_CONTACT",
  getCoupons: "GET_COUPONS",
  getCoupon: "GET_COUPON",
  getCouponBtn: "SET_COUPON_BTN",
  getPayouts: "GET_PAYOUTS",
  setPayout: "SET_PAYOUT",
};
export default ACTIONS;
